config/routes.rb
Rails.application.routes.draw do
 
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'welcome#index'
  controller :welcome do
    get :index
    get :home
    get :about
    get :contact_us
    get :bill_splitter
  end

  # # products new page - shows a form to create a product
  # get '/products/new', {to: 'products#new', as: :new_product}

  # # create products
  # post '/products', {to: 'products#create', as: :products}

  # # show product page
  # get '/products/:id', {to: 'products#show', as: :product}

  # # products index page
  # get '/products', {to: 'products#index'}

  # # product edit page
  # get '/products/:id/edit', {to: 'products#edit', as: :edit_product}

  # # update action handles the submission of form from the product edit page
  # patch '/products/:id', {to: 'products#update'}

  # # delete product and then redirect to the index page
  # delete '/products/:id', {to: 'products#destroy', as: :delete_product}

  # API
  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :products
      resource :session, only: [:create, :destroy]
      # /api/v1/user
      resources :users, only: [:create] do
      # api/v1/user/current
      get :current, on: :collection
      # default
      # api/v1/user/:id/current
      end
    end
  end
  
  # routes of reviews
  resources :products do
    resources :reviews, only: [:create, :destroy] do
      resources :likes, shallow: true, only: [:create, :destroy]
    end
  end
  
  resources :users, only: [:new, :create]

  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end

  resources :news_articles, only: [:new, :create, :show, :destroy, :index]

  resources :tags, only: [:index]
  
  # routes to delayed_job_web
  match "/delayed_job" => DelayedJobWeb, :anchor => false, :via => [:get, :post]

  # routes to admin
  get "/admin/panel", to: "admin#index"

end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
      user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
    
    alias_action :create, :read, :edit, :update, :destroy, to: :crud

    can :crud, Product do |product|
      product.user == user
    end

    can :crud, Review do |review|
      review.user == user
    end
    
    # The owner of the review cannot like its review
    can :like, Review do |review|
      user.persisted? && user != review.user
    end
    
    # ONLY the owner of the like can destroy the like
    can :destroy, Like do |like|
      like.user == user
    end

    # For admin
    if user.is_admin?
      can :manage, :all
    else
      can :read, :all
    end
    
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :review

  validates(
    :review_id,
    uniqueness: {
      scope: :user_id,
      message: "has already been liked"
    }
  )
end

app/models/news_article.rb
class NewsArticle < ApplicationRecord
  #  In this case, if the user column is not filled, is not able to be saved? Validation failed?
  belongs_to :user
  
  validates :title, presence: true, uniqueness: true
  validates :description, presence: true
end

app/models/product.rb
class Product < ApplicationRecord
  
  # Associations
  has_many :reviews, dependent: :destroy
  belongs_to :user

  has_many :taggings, dependent: :destroy
  has_many :tags, through: :taggings
  
  # Validations
  validates(:title, presence: true, uniqueness: { case_sensitive: false })
  validates(
    :description, presence: {message: "must exist"}, length: { minimum: 10 }
  )
  validates(:price, presence: true, numericality: { greater_than: 0 })

  # before_action
  before_validation :set_default_price
  before_save :capitalize_the_product
  
  # # Custom Getter & Setter
  # def tag_names
  #   self.tags.map{ |t| t.name }.join(", ")
  # end

  # def tag_names=(rhs)
  #   self.tags = rhs.strip.split(/\s*,\s*/).map do |tag_name|
  #     Tag.find_or_initialize_by(name: tag_name)
  #   end
  # end

  private

  def set_default_price
    self.price ||= 1
  end

  def capitalize_the_product
    self.title.capitalize!
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :product
  belongs_to :user

  # Many to Many
  has_many :likes, dependent: :destroy
  has_many :likers, through: :likes, source: :user

  # Validate that body is optional but the rating is required and must be a number between 1 and 5 inclusive.
  validates :rating, presence: true, numericality: { 
    only_integer: true, 
    greater_than_or_equal_to: 0,
    less_than_or_equal_to: 5
    }
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :taggings, dependent: :destroy
  has_many :products, through: :taggings

  validates :name, presence: true, uniqueness: { case_sensitive: false}

  before_validation :downcase_name

  private

  def downcase_name
    self.name&.downcase!
  end
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :tag
  belongs_to :product

  validates :tag_id, uniqueness: { scope: :product_id }
end

app/models/user.rb
class User < ApplicationRecord
  # password
  has_secure_password
  
  has_many :products, dependent: :nullify
  has_many :reviews, dependent: :nullify
  has_many :news_articles, dependent: :destroy

  # likes (many to many)
  has_many :likes, dependent: :destroy
  has_many :liked_reviews, through: :likes, source: :review
  
  # Validation
  validates :email, presence: true, uniqueness: true

  def full_name
    "#{first_name} #{last_name}".strip
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController

  def index
    redirect_to root_path unless can? :view_adminpanel, ""
    @products = Product.all
    @reviews = Review.all
    @users = User.all
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

  def index
    @tags = Tag.all
  end

end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
 
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/index.html.erb
<article>
  <div>
    <h2>Admin Panel</h2>
    <p>Number of Products: <%= @products.count %></p>
    <p>Number of Reviews: <%= @reviews.count %></p>
    <p>Number of Users: <%= @users.count %></p>
  </div>

  <div>
    <h3>Products</h3>
    <% @products.each do |product| %>
      <div>
        <%= product.id %> | <%= link_to product.title, product_path(product) %>
      </div>
    <% end %>
  </div>

  <div>
      <h3>Users</h3>
      <% @users.each do |user| %>
        <div>
          <%= user.id %> | <%= user.full_name %> (<%= user.email %>)
        </div>
      <% end %>
  </div>
</article>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Amazon</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <% flash.each do |type, message| %>
      <div class="flash flash-<%= type %>">
        <%= message %>
      </div>
    <% end %>

    <div class="d-flex flex-row justify-content-between bg-light">
      <h5 class="text-primary my-auto mx-3">Amazon</h5>
      <ul class="nav mx-3">
        <li class="nav-item"><%= link_to 'Home', products_path, class:"nav-link"%></li>
        <li class="nav-item"><%= link_to 'New Product', new_product_path, class:"nav-link"%></li>
        <li class="nav-item"><%= link_to 'All Products', products_path, class:"nav-link"%></li>
        <li class="nav-item"><%= link_to 'All Tags', tags_path, class:"nav-link"%></li>

        <% if user_signed_in? %>
          <li class="nav-item greeting">Hello, <%= current_user.full_name %></li>
          <li class="nav-item"><%= link_to 'Log Out', sessions_path, method: :delete, data: {confirm: "Are you sure you want to log out?"}, class:"nav-link" %></li>
        <% else %>
          <li class="nav-item"><%= link_to "Log In", new_session_path, class:"nav-link" %></li>
          <li class="nav-item"><%= link_to "Sign Up", new_user_path, class:"nav-link" %></li>
        <% end %>
      </ul>
    </div>
    <%= yield %>
  </body>
</html>