config/routes.rb
Rails.application.routes.draw do
 
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'welcome#index'
  controller :welcome do
    get :index
    get :home
    get :about
    get :contact_us
    get :bill_splitter
  end

  # # products new page - shows a form to create a product
  # get '/products/new', {to: 'products#new', as: :new_product}

  # # create products
  # post '/products', {to: 'products#create', as: :products}

  # # show product page
  # get '/products/:id', {to: 'products#show', as: :product}

  # # products index page
  # get '/products', {to: 'products#index'}

  # # product edit page
  # get '/products/:id/edit', {to: 'products#edit', as: :edit_product}

  # # update action handles the submission of form from the product edit page
  # patch '/products/:id', {to: 'products#update'}

  # # delete product and then redirect to the index page
  # delete '/products/:id', {to: 'products#destroy', as: :delete_product}

  # API
  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :products
      resource :session, only: [:create, :destroy]
      # /api/v1/user
      resources :users, only: [:create] do
      # api/v1/user/current
      get :current, on: :collection
      # default
      # api/v1/user/:id/current
      end
    end
  end
  
  # routes of reviews
  resources :products do
    resources :reviews, only: [:create, :destroy] do
      resources :likes, shallow: true, only: [:create, :destroy]
    end
  end
  
  resources :users, only: [:new, :create]

  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end

  resources :news_articles, only: [:new, :create, :show, :destroy, :index]

  resources :tags, only: [:index]
  
  # routes to delayed_job_web
  match "/delayed_job" => DelayedJobWeb, :anchor => false, :via => [:get, :post]

  # routes to admin
  get "/admin/panel", to: "admin#index"

end

app/models/product.rb
class Product < ApplicationRecord
  
  # Associations
  has_many :reviews, dependent: :destroy
  belongs_to :user

  has_many :taggings, dependent: :destroy
  has_many :tags, through: :taggings
  
  # Validations
  validates(:title, presence: true, uniqueness: { case_sensitive: false })
  validates(
    :description, presence: {message: "must exist"}, length: { minimum: 10 }
  )
  validates(:price, presence: true, numericality: { greater_than: 0 })

  # before_action
  before_validation :set_default_price
  before_save :capitalize_the_product
  
  # # Custom Getter & Setter
  # def tag_names
  #   self.tags.map{ |t| t.name }.join(", ")
  # end

  # def tag_names=(rhs)
  #   self.tags = rhs.strip.split(/\s*,\s*/).map do |tag_name|
  #     Tag.find_or_initialize_by(name: tag_name)
  #   end
  # end

  private

  def set_default_price
    self.price ||= 1
  end

  def capitalize_the_product
    self.title.capitalize!
  end
end

app/controllers/api/v1/products_controller.rb
class Api::V1::ProductsController < Api::ApplicationController
  before_action :authenticated_user!, except: [:index, :show]
  before_action :find_product, only: [:show, :destroy, :update]

  def index
    products = Product.order(created_at: :desc)
    render json: products
  end

  def show
    render json: @product
  end

  def create
    product = Product.new product_params
    product.user = current_user

    if product.save
      render json: { id: product.id }
    else 
      render(
        json: { errorss: product.errors },
        status: 422 
      )
    end
  end

  def destroy
    @product.destroy
    render json: { status: 200}, status: 200
  end

  def update
    if @product.update product_params
      render json: { id: @product.id, title: @product.title }
    else
      render(
        json: { errors: @product.errors },
        status: 422
      )
    end
  end

  private

  def find_product
    @product ||= Product.find params[:id]
  end

  def product_params
    params.require(:product).permit(:title, :description, :price)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  
  before_action :authenticate_user!, except: [:index, :show]

  before_action :find_product, only: [:show, :edit, :update, :destroy]
  before_action :authorize!, only: [:edit, :update, :destroy]

  def new
    @product = Product.new
    render :new
  end

  def create
    @product = Product.new product_params
    @product.user = current_user

    if @product.save
      ProductMailer.new_product(@product).deliver_later
      flash[:notice] = "Product created successfully"
      redirect_to product_path(@product)
    else
      render :new
    end

  end

  def show
    @product = Product.find(params[:id])
    @review = Review.new
    @reviews = @product.reviews.order(created_at: :desc)
  end

  def index
    if params[:tag]
      @tag = Tag.find_or_initialize_by(name: params[:tag])
      @products = @tag.products.order(created_at: :desc)
    else
      @products = Product.all
    end
  end

  def destroy
    flash[:notice] = "Product destroyed!"
    @product.destroy
    redirect_to products_path
  end

  def edit
  end

  def update
    #for user to update the existing question, they must edit and then save it
  
    if @product.update(product_params)
      redirect_to product_path(@product)
    else
      render :edit
    end
  end


  private

  def product_params
    #params.require(:question): we must have a question object on the params of this request
    params.require(:product).permit(:title, :description, :price, {tag_ids: []})
  end

  def find_product
    #this will get the current value inside of the db
    @product = Product.find params[:id]
  end
  
  def authorize!
    redirect_to root_path, alert: 'Not Authorized' unless can?(:crud, @product)
  end

end

app/helpers/api/v1/products_helper.rb
module Api::V1::ProductsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
 
end

app/views/products/_form.html.erb
<% if @product.errors.any? %>
    <ul>
        <% @product.errors.full_messages.each do |msg|%>
        <li><%=msg%></li>
        <% end %>
    </ul>

<%end%>


<%= form_for @product do |f|%>

    <div>
        <%= f.label :title %>
        <%= f.text_field :title %>
    </div>
    <div>
        <%= f.label :description %>
        <%= f.text_field :description %>
    </div>
    <div>
        <%= f.label :price %>
        <%= f.text_field :price %>
    </div>
    <div class="form-group">
        <%= f.collection_check_boxes :tag_ids, Tag.order(name: :asc), :id, :name do |b| %>
            <div class="tag-wrapper">
                <%= b.check_box %>
                <%= b.text.humanize %>
            </div>
        <% end %>
    </div>
    <%= f.submit %>

<%end%>

app/views/products/_list.html.erb
<% @products.each do |product| %>
  <div>
    <h2><%= link_to product.title, product_path(product) %></h2>
    <p><%= product.description %></p>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Eidt Your Product</h1>

<%= render 'form' %>

app/views/products/index.html.erb
<h3>All Products</h3>

<% if @tag.present? %>
  <h6>
    Showing questions tagged by
    <span class="badge badge-pill badge-primary">
      <%= @tag.name %>
    </span>
  </h6>
<% end %>
<%= render 'list' %>

app/views/products/new.html.erb
<h1>Register New Product</h1>

<%= render "form" %>

app/views/products/show.html.erb
<h3>Show Page</h3>

<h1><%= @product.title%></h1>
<p><%= @product.description %></p>
<p><%= number_to_currency(@product.price) %></p>
<p>
  Tags: 
  <% @product.tags.each do |tag| %>
    <%= link_to tag.name,
                products_path(tag: tag.name),
                class: "badge badge-pill badge-primary"
    %>
  <% end %>
</p>
<p>Sold by: <%= @product.user&.full_name || 'DELETED' %></p>

<% if can?(:crud, @product) %>
  <%= link_to "Edit", edit_product_path(@product) %>
  <%= link_to "Delete", product_path(@product), method: :delete, data: {confirm: "Are you sure?"} %>
<% end %>

<h3>Leave a review!</h3>

<%= form_with(model: [@product, @review], local: true) do |f| %>
  <% if @review.errors.any? %>
    <ul>
      <% @review.errors.full_messages.each do |msg|%>
        <li><%= msg %></li>
      <%end%>
    </ul>
  <%end%>

  <div>
    <%= f.text_area(
      :body,
      cols: 50,
      rows: 5,
      placeholder: "Please put honest reviews",
    )%>
    <br>
    <%= f.text_area(
      :rating,
      cols: 10,
      rows: 1,
      placeholder: "Number!"
    )%>
  </div>
  <%= f.submit "Save my Review!" %>
<% end %>

<hr />

<div>
<% if @reviews!= nil %>
<% @reviews.each do |review| %>
  <% @like = review.likes.find_by(user: current_user) %>

  <div>
    <p>
      <%= review.rating %> Star <br />
      <%= review.body %> <br />
      Reviewd by: <%= review.user&.full_name %> <br />
      
      <small>
        Commented <%= time_ago_in_words(review.created_at) %> ago
      </small>
    
      <% if can?(:crud, review) %>
        ●
        <small>
          <%= link_to(
            "Delete", 
            product_review_path(@product, review), 
            method: :delete,
            data: {
              confirm: "Are you sure?"
            })
          %>
        </small>
      <% end %>
    
      <% if @like.present? && can?(:destroy, @like) %>
        <%= link_to "Unlike👎", like_path(@like), method: :delete %>
      <% elsif can?(:like, review) %>
        <%= link_to "Like👍", product_review_likes_path(@product, review), method: :post %>
      <% end %>

      <small>
        (<%= pluralize(review.likes.count, "like") %>)
      </small>
    </p>
  </div>
<% end %>
<% end %>
</div>